### ISSUE TITLE
Impossible to remove dead link in Video section

### ISSUE THREAD

**Issue by LuisaUM** [urbaMonde/cohabitat-io-issue-tracker#1]
On this project: [Community Milton Park](https://www.cohabitat.io/en/projects/d34a049b-5bdf-4600-bb97-720f7b874c25/edit/videos)

### Expected behavior
The video should be removed when clicking "Remove"

### Actual behavior
Impossible to remove dead link of the video. Error:

The basics field is required when none of reversion to id / tags / texts / netlinks / properties / videos are present.
The reversion to id field is required when none of basics / tags / texts / netlinks / properties / videos are present.
The tags field is required when none of reversion to id / basics / texts / netlinks / properties / videos are present.
The texts field is required when none of reversion to id / tags / basics / netlinks / properties / videos are present.

### Screenshots

![image](https://user-images.githubusercontent.com/72458322/95222284-a0715d80-07f8-11eb-99ad-b11e7c468f0b.png)

### Environment
 - Device: PC 
 - OS: Windows 10
 - Chrome

**Comment by ntopulos** [comment]
Fixed by today's deployment.
